### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by bHorse** [EliMirren/Spring-generator#1]
@shenzhenMirren 
本项目我觉得最大的亮点在于Assist,工具,可以很灵活的拼装SQL
## 缺点
但是也有一个很大的缺点,在于每增加一张表,生成的mapper文件,都是一大堆重复的代码
## 改进方案
创建一个BaseDao的基类,所有的dao接口都可以继承,并使用泛型来确定Entity类
利用泛型,等方法来实现baseDao中所有的方法,这样起码可以减少大量的样板代码
相信实现改功能,将会是这个工具的一大进步

**Comment by shenzhenMirren** [comment]
群里回复你了,大家也可以自己做模板
