### ISSUE TITLE
在SQLServer2008下，无法获得数据库中的用户级别列表

### ISSUE THREAD

**Issue by l7810** [EliMirren/Spring-generator#3]
在master主干上的代码进行调试，发现DBUtil.java类中低86行，查询SQLServer用户级别表时，xtype=‘u’ 和v必须大写。考虑到SqlServer的版本兼容问题，建议jiang该sql字符串修改成“select name from sysobjects  where UPPER(xtype)='U' or UPPER(xtype)='V'”
![image](https://user-images.githubusercontent.com/12392453/49572907-b9e4bc80-f977-11e8-9929-2b027ad6f3d8.png)

**Comment by shenzhenMirren** [comment]
好的,我等一下改后提交
