### ISSUE TITLE
在非“_”字段的数据库表中，生成Entity对象时，理论上应该是将整个字段全部小写吧？

### ISSUE THREAD

**Issue by l7810** [EliMirren/Spring-generator#4]
在勾选驼峰命名选项时，master主干中，生成的实体对象，如果数据库中字段名不包含“_”时，仅将字段首字母小写，剩余字符保持不变。 
       理论上应该将整个字符串小写。
![tim 20181206181707](https://user-images.githubusercontent.com/12392453/49577797-2ca76500-f983-11e8-83e6-39a1a9b8d01f.png)

如果采纳这个建议，建议在StrUtil.java中，增加新的方法，来解决这种特殊情况。如：
![image](https://user-images.githubusercontent.com/12392453/49576834-113b5a80-f981-11e8-8d19-7e9ca9902ce2.png)

![tim 20181206180057](https://user-images.githubusercontent.com/12392453/49577506-80fe1500-f982-11e8-91da-e89e15f2b65e.png)

以上改法仅测试实体类，其他未做验证。

**Comment by shenzhenMirren** [comment]
这个问题如果人家已经是驼峰minName了也不太好，这个还是要靠用户命名规范比较好，后面我看一下做多一个是否为驼峰验证

**Comment by shenzhenMirren** [comment]
@l7810 嗯,后面加一个判断是否已经是驼峰了,如果不是再全部变小写,好像就oracle会默认大写吧,一般别的数据库不是人为输入都是小写,一般也要求统一小写
